apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "php-stack.fullname" . }}-git-config
  labels:
    {{- include "php-stack.labels" . | nindent 4 }}
data:
  GIT_REPO_URL: "{{ .Values.php.gitRepoUrl }}"
  GIT_REPO_TAG: "{{ .Values.php.gitRepoTag }}"
