apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "php-stack.fullname" . }}-php
  labels:
    {{- include "php-stack.php.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.php.replicaCount }}
  selector:
    matchLabels:
      {{- include "php-stack.php.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "php-stack.php.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: clone-repo
          image: alpine/git
          env:
            - name: GIT_REPO_URL
              value: ""  # Will be overridden by Rancher UI
            - name: GIT_REPO_TAG
              value: "main"  # Will be overridden by Rancher UI
          volumeMounts:
            - name: code
              mountPath: {{ .Values.php.gitDeployPath }}
          command:
            - sh
            - -c
            - |
              echo "Checking for git repository configuration..."
              echo "GIT_REPO_URL: $GIT_REPO_URL"
              echo "GIT_REPO_TAG: $GIT_REPO_TAG"
              if [ -n "$GIT_REPO_URL" ] && [ "$GIT_REPO_URL" != "" ]; then
                echo "Cloning repository: $GIT_REPO_URL (branch/tag: $GIT_REPO_TAG)"
                git clone --depth 1 --branch "$GIT_REPO_TAG" "$GIT_REPO_URL" {{ .Values.php.gitDeployPath }}
                echo "Repository cloned successfully!"
                ls -la {{ .Values.php.gitDeployPath }}
              else
                echo "No git repository configured. Creating default index.php..."
                echo "<?php phpinfo(); ?>" > {{ .Values.php.gitDeployPath }}/index.php
              fi
      containers:
        - name: php-apache
          image: "{{ .Values.php.image.registry }}/{{ .Values.php.image.repository }}:{{ .Values.php.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: code
              mountPath: {{ .Values.php.gitDeployPath }}
            {{- if .Values.php.uploads.enabled }}
            - name: uploads
              mountPath: {{ .Values.php.gitDeployPath }}/uploads
            {{- end }}
          resources:
            {{- toYaml .Values.php.resources | nindent 12 }}
          env:
            - name: PHP_ENABLE_OPCACHE
              value: "1"
            - name: GIT_REPO_URL
              value: ""  # Will be overridden by Rancher UI
            - name: GIT_REPO_TAG
              value: "main"  # Will be overridden by Rancher UI
            {{- range .Values.php.extraModules }}
            - name: PHP_ENABLE_{{ . | upper }}
              value: "1"
            {{- end }}
      volumes:
        - name: code
          emptyDir: {}
        {{- if .Values.php.uploads.enabled }}
        - name: uploads
          persistentVolumeClaim:
            claimName: {{ include "php-stack.fullname" . }}-uploads
        {{- end }}
