apiVersion: v1
kind: Service
metadata:
  name: {{ include "php-stack.fullname" . }}-php
  labels:
    {{- include "php-stack.php.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "php-stack.php.selectorLabels" . | nindent 4 }}
