apiVersion: v1
kind: Service
metadata:
  name: {{ include "php-stack.fullname" . }}-varnish
  labels:
    {{- include "php-stack.varnish.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.varnish.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "php-stack.varnish.selectorLabels" . | nindent 4 }}
